apiVersion: v1
kind: Service
metadata:
  name: lcw-dotnet-service
spec:
  selector:
    app: lcw-dotnet # Bu, Deployment'ın label'ı ile eşleşmeli
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP