apiVersion: v1
kind: Service
metadata:
  labels:
    app: lcw-dotnet
  name: lcw-dotnet
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30003
  selector:
    app: lcw-dotnet
  type: NodePort
